### PR TITLE
Hid Pattern.getGroup from the user.

### PR DESCRIPTION
**Pull request by ViddeM**

### CODE REVIEW

**Review by Jhogne — APPROVED** [review]
Looks good, but this pull request is very big. Consider breaking it down into multiple prs in the future for easier reviewing.

**Comment by ViddeM** [comment]
Yeah, I'm sorry. Sometimes I'm just really really lazy and don't feel like doing that.

**Comment by ericlp** [comment]
Shouldn't we aim to hide the majority of our project from the user? Ideally the user should only be able to create the Annotation and Pattern Enum.

**Comment by ViddeM** [comment]
Yes @ericlp yes but this is the most obvious entrypoint and a good starting point IMO.

**Review by ericlp — APPROVED** [review]

**Pull request merged**
