### PR TITLE
Add configuration necessary for using symbol solver

### PR DESCRIPTION
**Pull request by ViddeM**

### CODE REVIEW

**Review by ericlp — DISMISSED** [review]

**Comment by ViddeM** [comment]
I appear to be having some problems when using the symbol solver so I will wait with merging this until I have confirmed that this is correct.

**Review by lir108 — DISMISSED** [review]
Looks good

**Comment by ViddeM** [comment]
Should work now, removing blocked tag

**Review by ericlp — APPROVED** [review]

**Review by Jhogne — APPROVED** [review]
cool

**Pull request merged**
